// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Livro } from '../livro';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  async ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.livros = await this.servLivros.obterLivros();
  }

  excluir = async (codigo: string): Promise<void> => {
    await this.servLivros.excluir(codigo);
    this.livros = await this.servLivros.obterLivros();
  };

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}
<div class="container">
    <main>
      <h1>Catálogo de Livros</h1>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Título</th>
            <th>Editora</th>
            <th>Autores</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let livro of livros">
            <td>{{ livro.titulo }}</td>
            <td>{{ obterNome(livro.codEditora) }}</td>
            <td>
              <ul>
                <li *ngFor="let autor of livro.autores">{{ autor }}</li>
              </ul>
            </td>
            <td>
              <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
            </td>
          </tr>
        </tbody>
      </table>
    </main>
  </div>

// clientes/livros-react/src/LivroLista.js
import React, { useState, useEffect } from 'react';
import ControleLivro from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';

function LinhaLivro({ livro, excluir }) {
  const controleEditora = new ControleEditora();
  const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

  const handleExcluir = () => {
    excluir(livro.codigo);
  };

  return (
    <tr>
      <td>{livro.título}</td>
      <td>{nomeEditora}</td>
      <td>
        <button className="btn btn-danger" onClick={handleExcluir}>
          Excluir
        </button>
      </td>
    </tr>
  );
}

function LivroLista() {
  const controleLivro = new ControleLivro();
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      const livrosObtidos = await controleLivro.obterLivros();
      setLivros(livrosObtidos);
      setCarregado(true);
    };
    fetchData();
  }, [carregado]);

  const excluirLivro = async (codigo) => {
    await controleLivro.excluir(codigo);
    const livrosObtidos = await controleLivro.obterLivros();
    setLivros(livrosObtidos);
    setCarregado(false);
  };

  return (
    <main className="container mt-4">
      <h1 className="mb-4">Lista de Livros</h1>
      <table className="table">
        <thead style={{ backgroundColor: 'black', color: 'white' }}>
          <tr>
            <th>Título</th>
            <th>Editora</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro, index) => (
            <LinhaLivro key={index} livro={livro} excluir={excluirLivro} />
          ))}
        </tbody>
      </table>
    </main>
  );
}

export default LivroLista;
