// clientes/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import ControleLivro from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';
import { useNavigate } from 'react-router-dom';

function LivroDados() {
    const controleLivro = new ControleLivro();
    const controleEditora = new ControleEditora();
    const navigate = useNavigate();

    const opcoes = controleEditora.getEditoras().map(editora => ({
        value: editora.codEditora,
        text: editora.nome
    }));

    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(opcoes[0].value);

    const tratarCombo = (event) => {
        const { value } = event.target;
        setCodEditora(Number(value));
    };

    const incluir = async (event) => {
        event.preventDefault();
        const autoresArray = autores.split('\n');
        const novoLivro = {
            codigo: '', // Usando texto vazio para o código
            titulo,
            resumo,
            autores: autoresArray,
            codEditora
        };
        await controleLivro.incluir(novoLivro).then(() => navigate('/'));
    };

    return (
        <main className="container mt-4">
            <h1 className="mb-4">Novo Livro</h1>
            <form onSubmit={incluir}>
                <div className="mb-3">
                    <label htmlFor="titulo" className="form-label">Título</label>
                    <input type="text" className="form-control" id="titulo" value={titulo} onChange={(e) => setTitulo(e.target.value)} />
                </div>
                <div className="mb-3">
                    <label htmlFor="resumo" className="form-label">Resumo</label>
                    <textarea className="form-control" id="resumo" value={resumo} onChange={(e) => setResumo(e.target.value)}></textarea>
                </div>
                <div className="mb-3">
                    <label htmlFor="autores" className="form-label">Autores (um por linha)</label>
                    <textarea className="form-control" id="autores" value={autores} onChange={(e) => setAutores(e.target.value)}></textarea>
                </div>
                <div className="mb-3">
                    <label htmlFor="codEditora" className="form-label">Editora</label>
                    <select className="form-select" id="codEditora" value={codEditora} onChange={tratarCombo}>
                        {opcoes.map(opcao => (
                            <option key={opcao.value} value={opcao.value}>{opcao.text}</option>
                        ))}
                    </select>
                </div>
                <button type="submit" className="btn btn-primary">Salvar</button>
            </form>
        </main>
    );
}

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Livro } from '../livro';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro(1, 1, 'Título do Livro', 'Resumo do Livro', ['Autor 1', 'Autor 2']);
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  };
}
<main class="container">
    <h1>Cadastrar Livro</h1>
    <form (submit)="incluir()" ngNativeValidate>
      <div class="form-group">
        <label for="titulo">Título</label>
        <input type="text" id="titulo" class="form-control" [(ngModel)]="livro.titulo" name="titulo" required>
      </div>
      <div class="form-group">
        <label for="resumo">Resumo</label>
        <textarea id="resumo" class="form-control" [(ngModel)]="livro.resumo" name="resumo"></textarea>
      </div>
      <div class="form-group">
        <label for="editora">Editora</label>
        <select id="editora" class="form-control" [(ngModel)]="livro.codEditora" name="editora" required>
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>
      <div class="form-group">
        <label for="autores">Autores</label>
        <textarea id="autores" class="form-control" [(ngModel)]="autoresForm" name="autores"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Cadastrar</button>
    </form>
  </main>
